platform :ios, '8.0'
project 'HackerNewsReader.xcodeproj'

target 'HackerNewsReader' do

  # Pods for HackerNewsReader
  pod 'AFNetworking', '~>3.0'
  pod 'SDWebImage', '~>4.0'

  target 'HackerNewsReaderTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

